name: YaPlaceholder
version: 1.0.1
main: cn.ykdlb.yaplaceholder.YaPlaceholder
api-version: '1.13'
depend: [PlaceholderAPI]
authors: [APJifengc, Yoooooory]
description: Custom more advance Placeholder
