name: YaPlaceholder
version: 1.0.2
main: cn.ykdlb.yaplaceholder.YaPlaceholder
api-version: '1.13'
depend: [PlaceholderAPI]
authors: [APJifengc, Yoooooory]
description: An extension plugin of PlaceholderAPI that can let you custom advancer placeholders.